server:
  port: 8082
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/micro-hotel
    username: root
    password: Shubham3417@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8085
okta:
  oauth2:
    issuer: https://dev-63065601.okta.com/oauth2/default
    audience: api://default